# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
USER_LIB_PATH := $(realpath ../../libraries)
ARDUINO_LIBS = Adafruit_AHRS Adafruit_BNO055 Adafruit_Unified_Sensor BlueRobotics_MS5837_Library EEPROM Firmata SPI SensorFusion Servo SoftwareSerial Stepper Wire

include /usr/share/arduino/Arduino.mk
